### ISSUE TITLE
Script Crash

### ISSUE THREAD

**Issue by Dviros** [preempt/credssp#5]
Hi,
After running the script I got this error:

Tried 4050 primes...
Traceback (most recent call last):
  File "gen_cmd.py", line 182, in <module>
    main()
  File "gen_cmd.py", line 178, in main
    genCertAndPriv(args.certFile,args.privFile,args.E,n,d)
  File "gen_cmd.py", line 133, in genCertAndPriv
    replaceKey(certFile,a._save_pkcs1_der())
  File "gen_cmd.py", line 107, in replaceKey
    cert = Certificate.decode(s.decode('base64'))
  File "build/bdist.linux-x86_64/egg/ct/crypto/asn1/types.py", line 554, in decode

  File "build/bdist.linux-x86_64/egg/ct/crypto/asn1/types.py", line 502, in read

ct.crypto.error.ASN1TagError: Invalid tag: expected [UNIVERSAL 16], got  while decoding Certificate

**Comment by eyalk5** [comment]
You can actually report this in https://github.com/google/certificate-transparency.
Hmm, I thought it was older.
