### ISSUE TITLE
script crash

### ISSUE THREAD

**Issue by undefinedd** [preempt/credssp#9]
Traceback (most recent call last):
  File "gen_cmd.py", line 183, in <module>
    main()
  File "gen_cmd.py", line 179, in main
    genCertAndPriv(args.certFile,args.privFile,args.E,n,d)
  File "gen_cmd.py", line 125, in genCertAndPriv
    r = rsa.PrivateKey(n, e, d, p, q, exp1=e, exp2=e,coef=e)
TypeError: __init__() got an unexpected keyword argument 'exp2'

**Comment by ShakingPoP** [comment]
change the version of Module "rsa" to fix it. :)

**Comment by iamshleya** [comment]
I'm also running into this error. Changing the value of E doesn't seem to resolve it. Any other suggestions?

**Comment by undefinedd** [comment]
pip install rsa==3.2

**Comment by undefinedd** [comment]
> I'm also running into this error. Changing the value of E doesn't seem to resolve it. Any other suggestions?

Are you still paying attention to this project? I think we can talk about it.

**Comment by eyalk5** [comment]
So, I should have changed this in the install script? any other changes to pip modules?
